-- Auto-generated from Orenda quest catalog
INSERT INTO public.quest_subjects (id, label, sort_order) VALUES
  ('kaibou', '解剖学', 1),
  ('seiri', '生理学', 2),
  ('byouri', '病理学概論', 3),
  ('souron', '臨床医学総論', 4),
  ('kakuron', '臨床医学各論', 5),
  ('reha', 'リハビリテーション医学', 6),
  ('tougai', '東洋医学概論', 7),
  ('keiketu', '経絡経穴概論', 8),
  ('tourin', '東洋医学臨床論', 9),
  ('hari', 'はり理論', 10),
  ('kyu', 'きゅう理論', 11),
  ('iryogairon', '医療概論', 12),
  ('eisei', '衛生学・公衆衛生学', 13),
  ('kankeihouki', '関係法規', 14)
ON CONFLICT (id) DO UPDATE SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order;

INSERT INTO public.quest_subcategories (id, subject_id, label, sort_order) VALUES
  ('iryogairon-society', 'iryogairon', '医療と社会', 1),
  ('iryogairon-security', 'iryogairon', '社会保障制度', 2),
  ('iryogairon-ethics', 'iryogairon', '医療倫理', 3),
  ('eisei-meaning', 'eisei', '衛生・公衆衛生学の意義', 1),
  ('eisei-prevention', 'eisei', '健康の保持増進と疾病予防', 2),
  ('eisei-lifestyle', 'eisei', 'ライフスタイルと健康', 3),
  ('eisei-environment', 'eisei', '環境と健康', 4),
  ('eisei-industrial', 'eisei', '産業衛生管理', 5),
  ('eisei-mental', 'eisei', '精神保健', 6),
  ('eisei-maternal', 'eisei', '母子保健', 7),
  ('eisei-adult-elderly', 'eisei', '成人・高齢者保健', 8),
  ('eisei-infection', 'eisei', '感染症対策', 9),
  ('eisei-disinfection', 'eisei', '消毒', 10),
  ('eisei-epidemiology', 'eisei', '疫学', 11),
  ('eisei-statistics', 'eisei', '保健統計', 12),
  ('eisei-international', 'eisei', '国際保健', 13),
  ('eisei-school', 'eisei', '学校保健', 14),
  ('kankeihouki-license', 'kankeihouki', 'あはき法における免許', 1),
  ('kankeihouki-work', 'kankeihouki', 'あはき法における業務', 2),
  ('kankeihouki-penalty', 'kankeihouki', 'あはき法における罰則', 3),
  ('kankeihouki-law', 'kankeihouki', 'あはき法全般', 4),
  ('kankeihouki-related', 'kankeihouki', '関係法規', 5),
  ('kaibou-general', 'kaibou', '解剖学一般', 1),
  ('kaibou-skeleton', 'kaibou', '骨格系', 2),
  ('kaibou-muscle', 'kaibou', '筋系', 3),
  ('kaibou-viscera', 'kaibou', '内臓系', 4),
  ('kaibou-vascular', 'kaibou', '脈管系', 5),
  ('kaibou-nerve', 'kaibou', '神経系', 6),
  ('kaibou-sense', 'kaibou', '感覚器系', 7),
  ('seiri-basic', 'seiri', '生理学の基礎', 1),
  ('seiri-circulation', 'seiri', '循環', 2),
  ('seiri-respiration', 'seiri', '呼吸', 3),
  ('seiri-digestion', 'seiri', '消化と吸収', 4),
  ('seiri-metabolism', 'seiri', '代謝', 5),
  ('seiri-temperature', 'seiri', '体温', 6),
  ('seiri-excretion', 'seiri', '排泄', 7),
  ('seiri-endocrine', 'seiri', '内分泌', 8),
  ('seiri-reproduction', 'seiri', '生殖と成長', 9),
  ('seiri-nerve', 'seiri', '神経', 10),
  ('seiri-muscle', 'seiri', '筋肉', 11),
  ('seiri-movement', 'seiri', '身体の運動', 12),
  ('seiri-coordination', 'seiri', '身体活動の協調', 13),
  ('seiri-sense', 'seiri', '感覚', 14),
  ('seiri-defense', 'seiri', '生体の防御機構', 15),
  ('byouri-basic', 'byouri', '病理学の基礎', 1),
  ('byouri-cause', 'byouri', '病因', 2),
  ('byouri-circulation', 'byouri', '循環障害', 3),
  ('byouri-degenerative', 'byouri', '退行性病変（代謝障害）', 4),
  ('byouri-progressive', 'byouri', '進行性病変', 5),
  ('byouri-inflammation', 'byouri', '炎症', 6),
  ('byouri-immunity', 'byouri', '免疫異常とアレルギー', 7),
  ('byouri-tumor', 'byouri', '腫瘍', 8),
  ('byouri-congenital', 'byouri', '先天性異常', 9),
  ('souron-examination', 'souron', '診察法', 1),
  ('souron-lab', 'souron', '臨床検査法', 2),
  ('souron-treatment', 'souron', '治療法', 3),
  ('souron-psychology', 'souron', '臨床心理', 4),
  ('kakuron-infection', 'kakuron', '感染症', 1),
  ('kakuron-neuromuscular', 'kakuron', '神経・筋疾患', 2),
  ('kakuron-respiratory', 'kakuron', '呼吸器・胸壁疾患', 3),
  ('kakuron-cardiovascular', 'kakuron', '循環器疾患', 4),
  ('kakuron-digestive', 'kakuron', '消化管疾患', 5),
  ('kakuron-urology', 'kakuron', '泌尿生殖器疾患', 6),
  ('kakuron-hematology', 'kakuron', '血液・造血器疾患', 7),
  ('kakuron-metabolism', 'kakuron', '代謝・栄養疾患', 8),
  ('kakuron-endocrine', 'kakuron', '内分泌疾患', 9),
  ('kakuron-autoimmune', 'kakuron', '自己免疫疾患', 10),
  ('kakuron-musculoskeletal', 'kakuron', '運動器疾患', 11),
  ('kakuron-dermatology', 'kakuron', '皮膚・頭頸部疾患', 12),
  ('kakuron-psychiatric', 'kakuron', '精神・心身医学的疾患', 13),
  ('kakuron-anesthesia', 'kakuron', '麻酔', 14),
  ('kakuron-functional', 'kakuron', '機能性疾患', 15),
  ('kakuron-surgery', 'kakuron', '一般外科', 16),
  ('kakuron-gynecology', 'kakuron', '婦人科疾患', 17),
  ('kakuron-pediatrics', 'kakuron', '小児科疾患', 18),
  ('kakuron-oral', 'kakuron', '口腔疾患', 19),
  ('kakuron-other', 'kakuron', 'その他', 20),
  ('reha-overview', 'reha', 'リハビリテーションの概要', 1),
  ('reha-medical', 'reha', '医学的リハビリテーションの概要', 2),
  ('reha-assessment', 'reha', '障害の評価', 3),
  ('reha-medical-rehab', 'reha', '医学的リハビリテーション', 4),
  ('reha-kinesiology', 'reha', '運動学の基盤', 5),
  ('reha-stroke', 'reha', '脳卒中のリハビリテーション', 6),
  ('reha-spinal', 'reha', '脊髄損傷のリハビリテーション', 7),
  ('reha-amputation', 'reha', '切断', 8),
  ('reha-cp', 'reha', '脳性麻痺', 9),
  ('reha-orthopedic', 'reha', '整形外科・運動器疾患', 10),
  ('reha-respiratory', 'reha', '呼吸器疾患', 11),
  ('reha-cardiac', 'reha', '心疾患', 12),
  ('reha-elderly', 'reha', '高齢者のリハビリテーション', 13),
  ('tougai-basic', 'tougai', '東洋医学の基礎', 1),
  ('tougai-qi-blood', 'tougai', '気血・津液の生理', 2),
  ('tougai-zangfu', 'tougai', '五臓六腑', 3),
  ('tougai-zofu-keiraku', 'tougai', '臓腑経絡論', 4),
  ('tougai-etiology', 'tougai', '病因論', 5),
  ('tougai-pathology', 'tougai', '病理と症証', 6),
  ('tougai-diagnosis', 'tougai', '東洋医学的診察法と証の立て方', 7),
  ('tougai-treatment', 'tougai', '治療法', 8),
  ('keiketu-basic', 'keiketu', '経絡・経穴の基礎', 1),
  ('keiketu-fourteen', 'keiketu', '十四経脈の取穴法', 2),
  ('keiketu-extra', 'keiketu', '奇経・奇穴', 3),
  ('keiketu-important', 'keiketu', '要穴', 4),
  ('keiketu-research', 'keiketu', '経絡・経穴の現代医学的研究', 5),
  ('tourin-diagnosis-treatment', 'tourin', '診断と治療', 1),
  ('tourin-records', 'tourin', '診察と記録', 2),
  ('tourin-treatment-basic', 'tourin', '施術の基礎', 3),
  ('tourin-symptom-approach', 'tourin', '症候に対するアプローチ', 4),
  ('tourin-western-approach', 'tourin', '西洋医学からのアプローチ', 5),
  ('tourin-oriental-approach', 'tourin', '東洋医学からのアプローチ', 6),
  ('tourin-elderly', 'tourin', '高齢者に対する施術', 7),
  ('tourin-sports', 'tourin', 'スポーツ領域', 8),
  ('tourin-industrial', 'tourin', '産業衛生', 9),
  ('tourin-health', 'tourin', '健康と鍼灸', 10),
  ('tourin-other', 'tourin', 'その他', 11),
  ('hari-basic', 'hari', '鍼の基礎知識', 1),
  ('hari-technique', 'hari', '基本的な刺鍼方法', 2),
  ('hari-special', 'hari', '特殊鍼法', 3),
  ('hari-clinical', 'hari', '鍼の臨床応用', 4),
  ('hari-risk', 'hari', 'リスク管理', 5),
  ('hari-treatment-basic', 'hari', '鍼治効の基礎', 6),
  ('hari-theory', 'hari', '鍼療法の治効理論', 7),
  ('hari-related', 'hari', '関連学説', 8),
  ('kyu-basic', 'kyu', '灸の基礎知識', 1),
  ('kyu-types', 'kyu', '灸術の種類', 2),
  ('kyu-clinical', 'kyu', '灸の臨床応用', 3),
  ('kyu-risk', 'kyu', 'リスク管理', 4),
  ('kyu-theory', 'kyu', '灸治効の基礎', 5),
  ('kyu-efficacy-theory', 'kyu', '灸療法の治効理論', 6),
  ('kyu-related', 'kyu', '関連学説', 7)
ON CONFLICT (id) DO UPDATE SET subject_id = EXCLUDED.subject_id, label = EXCLUDED.label, sort_order = EXCLUDED.sort_order;
